### ISSUE TITLE
Plugin crashed

### ISSUE THREAD

**Issue by bluepioupiou** [annaet/cypress-tags-example#2]
I've got an error saying my plugin crashed...

`The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`C:\Users\abd0c6dn\Documents\workspace\victor\pc5-web-front\cypress\plugins\index.js`)

 TypeError: Cannot read property 'createNodeArray' of undefined
    at removeTagsFromNode (C:\Users\xxx\Documents\workspace\xxx\node_modules\cypress-tags\dist\index.js:92:42)
    at visit (C:\Users\xxx\Documents\workspace\xxx\node_modules\cypress-tags\dist\index.js:126:40)
    at C:\Users\xxx\Documents\workspace\xxx\node_modules\cypress-tags\dist\index.js:154:84
    ...
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
`

on version 0.0.17 with Cypress 6.1.0

**Comment by annaet** [comment]
@bluepioupiou `createNodeArray` is called off the TypeScript factory, so it's possible it's a typescript issue. Can you check what version of TypeScript you have installed?

**Comment by bluepioupiou** [comment]
I've got typescript version 3.1.3

**Comment by annaet** [comment]
I'm using version 4.0.5 at the moment. Can you try upgrading to v4 and see if that fixes the issue?

**Comment by bluepioupiou** [comment]
ok, I'll try and keep you informes, thanks

**Comment by bluepioupiou** [comment]
it's working. Thanks a lot for this pluging and your quick reaction
